dataset:
    name: 'dataset'
    max_samples: 1

annotator:
    method : ''

predictor:
    method : 't2i'
    config:
        t2i:
            type: 'OpenAI'
            name: 'dall-e-3' #'stable-diffusion-xl-1024-v1-0'
            "image_size": "1024x1024"
            "quality": "standard"
            "output_path": ''
        mode: 'prediction'

meta_prompts:
    folder: 'prompts/meta_prompts_image_generation'

eval:
    function_name: 'dsg_score'
    llm:
        type: 'OpenAI'
        name: 'gpt-4o'
    num_workers: 1
    source_image_folder: '/Users/nirvivakharia/Documents/CVPRPaper2024/sourceImageFolder'
    num_large_errors: 4
    error_threshold: 5
llm:
    type: 'OpenAI'
    name: 'gpt-4o'
    temperature: 0.8
